name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on semantic version tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'  # Use your target .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Extract version from tag
        id: get_version
        run: echo "##[set-output name=VERSION;]${GITHUB_REF#refs/tags/v}"

      - name: Build the solution
        run: dotnet build --configuration Release

      - name: Pack the NuGet package with dynamic version
        run: dotnet pack --configuration Release /p:PackageVersion=${{ steps.get_version.outputs.VERSION }} --output ./nupkgs

      - name: Authenticate with GitHub Packages
        run: dotnet nuget add source https://nuget.pkg.github.com/pa-nihr-crn/index.json -n github --username pa-nihr-crn --password ${{ secrets.GITHUB_TOKEN }}

      - name: Push NuGet package to GitHub Packages
        run: dotnet nuget push ./nupkgs/*.nupkg --source github --api-key ${{ secrets.GITHUB_TOKEN }}